"""Fix attendance FK with ON UPDATE CASCADE

Revision ID: 134d228693a9
Revises: 89c678700833
Create Date: 2025-11-02 21:07:32.435758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134d228693a9'
down_revision = '89c678700833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classeses", schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_user_role'))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)

    with op.batch_alter_table("classeses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)

    # ### end Alembic commands ###
