"""Add weight to assignments

Revision ID: 19f0607e3560
Revises: f9217bee10f1
Create Date: 2025-11-01 17:09:58.658850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f0607e3560'
down_revision = 'f9217bee10f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), server_default='1.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
