"""add grade/feedback to project_submissions

Revision ID: 540369e22fb4
Revises: 7b3c2a9751b0
Create Date: 2025-11-15 11:56:15.808374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540369e22fb4'
down_revision = '7b3c2a9751b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('graded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('idx_user_role'))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        pass

    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.drop_column('graded_at')
        batch_op.drop_column('feedback')
        batch_op.drop_column('grade')

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    # ### end Alembic commands ###
