"""Add fingerprint to attendance

Revision ID: 5fd566c15286
Revises: f4023ee0cc15
Create Date: 2025-11-20 22:59:11.199756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd566c15286'
down_revision = 'f4023ee0cc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_attendance_fingerprint'), ['fingerprint'], unique=False)
        pass

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_fingerprint'))
        batch_op.drop_column('fingerprint')
        pass

    # ### end Alembic commands ###
