"""Add ON UPDATE CASCADE to wechat_users FK

Revision ID: 611eac9a2169
Revises: 134d228693a9
Create Date: 2025-11-02 21:50:12.579902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611eac9a2169'
down_revision = '134d228693a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classeses", schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_user_role'))
        pass 

    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('wechat_users_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key('wechat_users_ibfk_1', 
        'user', ['student_id'], ['student_id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_users', schema=None) as batch_op:
        batch_op.drop_constraint('wechat_users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wechat_users_ibfk_1'), 'user', 
        ['student_id'], ['student_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        pass

    with op.batch_alter_table("classeses", schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    # ### end Alembic commands ###
