"""add created_at to user

Revision ID: 64014669378e
Revises: ee16a81597a7
Create Date: 2025-11-19 07:31:29.187410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64014669378e'
down_revision = 'ee16a81597a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    # ### end Alembic commands ###
