"""Added email_verified totp_secret to user

Revision ID: 7bd93e288dd1
Revises: 9626dc43880a
Create Date: 2025-11-18 22:06:35.466553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd93e288dd1'
down_revision = '9626dc43880a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        #batch_op.drop_index(batch_op.f('idx_user_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    # ### end Alembic commands ###
