"""Update attendance.student_id FK with CASCADE

Revision ID: 89c678700833
Revises: 19f0607e3560
Create Date: 2025-11-02 20:41:04.369492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c678700833'
down_revision = '19f0607e3560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table("classeses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_enrolled_class'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)

    with op.batch_alter_table("classeses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_ibfk_2'), 'user', ['student_id'], ['student_id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
