"""add anti-cheat fields

Revision ID: 9626dc43880a
Revises: c86ad8dec11b
Create Date: 2025-11-18 10:11:29.671737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9626dc43880a'
down_revision = 'c86ad8dec11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('login_fingerprint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('login_ua', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('force_logout', sa.Boolean(), nullable=True))
        #batch_op.drop_index(batch_op.f('idx_user_role'))
        batch_op.create_index(batch_op.f('ix_user_login_token'), ['login_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_token'))
        #batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        batch_op.drop_column('force_logout')
        batch_op.drop_column('login_at')
        batch_op.drop_column('login_ua')
        batch_op.drop_column('login_ip')
        batch_op.drop_column('login_fingerprint')
        batch_op.drop_column('login_token')

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    # ### end Alembic commands ###
