"""project_submissions id starts from 1000000

Revision ID: b9a45fb44143
Revises: 540369e22fb4
Create Date: 2025-11-15 12:18:56.945795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a45fb44143'
down_revision = '540369e22fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass
    with op.batch_alter_table('user', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_user_role'))
        pass
    # 设置自增序列从 1000000 开始
    op.execute("ALTER TABLE project_submissions AUTO_INCREMENT = 1000000")
    # 或使用 SQLAlchemy 方式
    op.alter_column('project_submissions', 'id',
                    existing_type=sa.Integer(),
                    autoincrement=True,
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        pass

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass
    
    
    op.execute("ALTER TABLE project_submissions AUTO_INCREMENT = 1")
    # ### end Alembic commands ###
