"""add qq_users Attendance WeChatUser

Revision ID: eb1a6fe6e146
Revises: abe1cc92213c
Create Date: 2025-10-29 10:35:50.984582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1a6fe6e146'
down_revision = 'abe1cc92213c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qq_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('bind_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qq_users')
    # ### end Alembic commands ###
