"""add email verification

Revision ID: ee16a81597a7
Revises: 7bd93e288dd1
Create Date: 2025-11-19 06:24:18.508400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee16a81597a7'
down_revision = '7bd93e288dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_user_role'))
        batch_op.create_unique_constraint(None, ['email_verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    # ### end Alembic commands ###
