"""User add reset_token reset_token_expires

Revision ID: ee45ead654f6
Revises: 5fd566c15286
Create Date: 2025-11-21 07:42:38.659106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee45ead654f6'
down_revision = '5fd566c15286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.drop_index(batch_op.f('idx_enrolled_class'))
        pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('enrolled_classes', schema=None) as batch_op:
        #batch_op.create_index(batch_op.f('idx_enrolled_class'), ['class_id', 'user_id'], unique=False)
        pass

    # ### end Alembic commands ###
